[versions]
# Android SDK versions
compileSdk = "36"
minSdk = "30"
targetSdk = "36"

# Library versions
activityCompose = "1.10.1"
agp = "8.10.0"
coil = "3.2.0"
composeBom = "2024.09.00"
coreKtx = "1.16.0"
espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kmpSampleLibrary = "1.2.0"
koin = "4.1.0"
kotlin = "2.2.0"
lifecycleRuntimeKtx = "2.9.1"


[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kmp-sample-library-shared = { group = "io.github.kei_1111.kmp_sample_library", name = "shared", version.ref = "kmpSampleLibrary" }
kmp-sample-library-home = { group = "io.github.kei_1111.kmp_sample_library", name = "home", version.ref = "kmpSampleLibrary" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }

# Use build-logic
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# kmp-sample-android
kmp-sample-android-application = { id = "kmp.sample.android.application" }
kmp-sample-android-feature = { id = "kmp.sample.android.feature" }
kmp-sample-android-library-compose = { id = "kmp.sample.android.library.compose" }
kmp-sample-android-library = { id = "kmp.sample.android.library" }